version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: v18
  pre_build:
    commands:
      - echo Build started on `date`
      - npm install
  build:
    commands:
      - echo Build Not Required
      - node app.js
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"